name: Semver
description: Substitute variables for JSON/XML - first release will support JSON
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}  
  prefix:
    required: true
    default: ''
  prerelease:
    required: false
    default: no
  REQUIRE_PRERELEASE:
    required: false
    default: 'true'
  starts-with:
    required: false
    default: ''
  
outputs:
  version:
    description: version
runs:
  using: "node20"
  main: src/index.js